networks:
  gosts:

services:
  postgres:
    image: postgres:latest
    container_name: gosts-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gosts
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - gosts
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - gosts

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    image: gosts-backend # название образа
    container_name: gosts-backend-container
    networks:
      - gosts

  frontend:
    build:
      context: ./frontend
    image: gosts-frontend # название образа
    container_name: gosts-frontend-container
    networks:
      - gosts
    ports:
      - "3000:3000"

volumes:
  pgdata:
    driver: local